[package]
name = "smart-road"
version = "0.1.0"
authors = ["tathienbao <tathienbao.ttb@gmail.com>"]
edition = "2021"

[dependencies.sdl2]
version = "0.35.2"
default-features = false
features = ["gfx"]