[package]
name = "smart-road"
version = "0.1.0"
authors = ["tathienbao <tathienbao.ttb@gmail.com>"]
edition = "2021"

[dependencies]
rand = { version = "0.8.5", features = [] }
piston_window = "0.130.0"
piston-gfx_texture = "0.44.0"
image = { version = "0.24.7", features = [] }
kurbo = "0.9.5"




